[project]
name = "deal-watcher"
version = "1.0.2"
description = "Watch subreddits and RedFlagDeals RSS for new posts and notify you instantly via Telegram"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4==4.12.3",
    "croniter==3.0.3",
    "fake-useragent==2.0.3",
    "feedparser==6.0.11",
    "python-crontab==3.2.0",
    "python-dateutil==2.9.0",
    "python-dotenv==1.0.1",
    "python-telegram-bot==21.6",
    "requests==2.32.3",
]

[tool.uv]
exclude-newer = "7 days"
